### ISSUE TITLE
Messaging on the live server

### ISSUE THREAD

**Issue by kahill2014** [kahill2014/Hmong-Project#1]
This is just a note to let everyone know that the messaging does not yet work on the live server, but should work locally. This may mean having to set up a local phpmyadmin (or potentially just using washington) until I (or anyone) can figure out why it (PHP files?) doesn't load there.

**Comment by paulknisely** [comment]
What version of php was this code used with? Messing around with the php command, the files are returning errors and changing the db_connect.php file like so:
```
<?php
require ("config.php");
 //This part attempts to open a connection to the host of the database with the specified username and password
    //$connection = mysql_connect("$DBHOST","$DBUSER","$DBPASSWORD") 
    $connection = new mysqli($DBHOST, $DBUSER, $DBPASSWORD)
    or die ("Couldn't connect to server.");

    //This part actually selects the database from any others on the server and lets you select tables to get data from and insert into and stuff
    //$db = mysql_select_db("$DBNAME", $connection)
    $db = mysqli_select_db($connection, "$DBNAME")
    or die("Couldn't select database.");
?>

```
removed the errors so I think the server version is higher then the code supplied. This server is at 7.0.28, washington is at 5.3.17.

**Comment by kahill2014** [comment]
Updated to PHP 7 and it is working now.
