### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by weyrougham10** [kahill2014/Hmong-Project#3]
As of right now I have simple code to upload the image selected to mysql. The main issue is I couldn't figure out how to use the databaseConnection/pdo_connect.php. I had to create my own database connection within my code.

**Comment by paulknisely** [comment]
Fixed issue with [this commit](https://github.com/kahill2014/Hmong-Project/commit/330ad7ce2be6233f61624eef9121894cc0366ca0).
